version: "3"
services:
  selenium:
    image: selenium/standalone-chrome:latest
    volumes:
      - "/dev/shm:/dev/shm"
    ports:
      - "4444:4444"
    environment:
      - NODE_MAX_INSTANCES=4
      - NODE_MAX_SESSION=4
  thirtyfour_testapp:
    build:
      context: .
    image: stevepryde/thirtyfour_testapp:latest
    ports:
      - "8000:80"
